CREATE_RECORD_TABLE = '''
CREATE TABLE IF NOT EXISTS records (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   time STRING NOT NULL
)'''

INSERT_RECORD = "INSERT INTO records (time) VALUES ('{time}')"

GET_ALL_RECORDS = "SELECT * FROM records ORDER BY time ASC"

GET_TOP_3_RECORDS = "SELECT * FROM records ORDER BY time ASC LIMIT 3"

GET_LAST_3_RECORDS = "SELECT * FROM records ORDER BY id DESC LIMIT 3"
